### PR TITLE
Add Draft To Multi Process Workflows

### PR DESCRIPTION
**Pull request by huzaifa-99**
**Issue/s:**
https://github.com/eLearningDAO/POCRE/issues/282

### CODE REVIEW

**Review by AltiMario — COMMENTED** [review]
I did a general test, the saving process was ok (going back and forward the draft) but "related" issues such as #306, #304 and #275 did not allow me to complete the use case.

**Comment by AltiMario** [comment]
I still cannot save 2 materials 
image
but only one is allowed.
I'm using the deploy preview https://deploy-preview-299--pocre.netlify.app/

**Comment by AltiMario** [comment]
I did a creation with 2 materials and before saving draft I went back to the home. The system saved the creation but not the mateials (I had to add them again)
image

**Comment by UmairMukhtar** [comment]
> @UmairMukhtar there is still a regression left from #301.
> 
> I took the time to debug and this line (https://github.com/eLearningDAO/POCRE/pull/299/files#diff-bd830bf780628696ffd760b5232cda82258f723fd6453111f2c24bdcf841d6d5R84) breaks the code. image
> 
> This is the error in console. image
> 
> To reproduce
> 
>     1. Create a draft creation with more than 2 material authors (the authors must have a star in their name)
> 
>     2. Visit creation home page
> 
>     3. Select the draft creation and click on the edit button
> 
>     4. Now without any changes, try to press the 'Save Draft' on step 3
> 
>     5. Notice it does nothing and throws error (see console)

done in another pull request
https://github.com/eLearningDAO/POCRE/pull/310/commits/1c0ebc6ee56a430db8290342167dd1685833f345#

**Pull request merged**
